spring.application.name=gestao-tarefas

# 1. Verifique se o nome do banco está exatamente igual ao que você criou (recomenda-se minúsculo)
spring.datasource.url=jdbc:postgresql://localhost:5432/Tarefas

spring.datasource.username=admin

# 3. Certifique-se de que essa é a senha que você escolheu na instalação do Postgres
spring.datasource.password=admin123

# Driver do PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect